### ISSUE TITLE
Ranking Table Never Gets Pruned.

### ISSUE THREAD

**Issue by realrhys** [Volentix/venue#139] opened 2018-08-15 20:11 UTC
**Describe the bug**
The Ranking table never prunes its records. The more uses the more records it creates. This effects the leader_board_data() StoredProc performance and begins to cripple it significantly.

The question is... do we need to keep all this data.

**To Reproduce**

This is a difficult one to reproduce as it requires time and a lot of uses. For now, I have a rds instance called venueperf that has enough data collected to fix the bug.

1. Backup the venueperf database.
2. Connect to the database with an sql client.
3. Run the call 'select public.leader_board_data(NUM, NUM, NUM)
4. Collect the timing results.
5. Prune records (or whatever it is that we plan on doing)
6. Do 3 & 4 again to see if its faster.

Note that you may need to restore the database if you need to test this multiple times.

**Expected behaviour**
Call should run in the 100's ms range.

**Screenshots**

**Desktop (please complete the following information):**
 - N/A

**Smartphone (please complete the following information):**
 - N/A

**Additional context**

**Comment by shawnlauzon** [comment] 2018-08-16 21:51
Duplicate of Volentix/venue-server#167

**Closed by shawnlauzon** 2018-08-16 21:51 UTC
